# Generated by Django 5.2.17 on 2026-08-06 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationMatricule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_profil', models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('PERSONNEL', 'Personnel')], max_length=20, unique=True)),
                ('prefixe', models.CharField(default='MAT', max_length=10)),
                ('inclure_annee', models.BooleanField(default=True)),
                ('nombre_chiffres', models.PositiveIntegerField(default=4)),
                ('separateur', models.CharField(default='-', max_length=3)),
                ('compteur', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('cni', models.FileField(blank=True, null=True, upload_to='etudiants/cni/')),
                ('diplome', models.FileField(blank=True, null=True, upload_to='etudiants/diplomes/')),
                ('acte_naissance', models.FileField(blank=True, null=True, upload_to='etudiants/actes_naissance/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='etudiants/photos/')),
                ('nom_tuteur', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone_tuteur', models.CharField(blank=True, max_length=20, null=True)),
                ('specialite', models.CharField(blank=True, max_length=150, null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('ABANDON', 'Abandon'), ('DIPLOME', 'Diplômé'), ('EXCLU', 'Exclu'), ('DEMISSIONNAIRE', 'Démissionnaire')], default='ACTIF', max_length=20)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('date_embauche', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('cni', models.FileField(blank=True, null=True, upload_to='personnel/cni/')),
                ('diplome', models.FileField(blank=True, null=True, upload_to='personnel/diplomes/')),
                ('motivation', models.FileField(blank=True, null=True, upload_to='personnel/motivations/')),
                ('recommandation', models.FileField(blank=True, null=True, upload_to='personnel/recommandations/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personnel/photos/')),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('poste', models.CharField(blank=True, max_length=100, null=True)),
                ('fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu'), ('ENCONGE', 'En congé'), ('RETRAITE', 'Retraité')], default='ACTIF', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('PERMANENT', 'Permanent'), ('VACATAIRE', 'Vacataire')], max_length=20)),
                ('filiere', models.CharField(blank=True, max_length=150, null=True)),
                ('specialite', models.CharField(blank=True, max_length=150, null=True)),
                ('personnel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formateur', to='utilisateurs.personnel')),
            ],
        ),
    ]
