# Generated by Django 5.2.17 on 2026-08-08 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigurationMatricule',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='academique.classe'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='academique.niveau'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='academique.specialite'),
        ),
    ]
