# Generated by Django 5.2.17 on 2026-08-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0001_initial'),
        ('utilisateurs', '0002_delete_configurationmatricule_etudiant_classe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formateur',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='formateur',
            name='specialite',
        ),
        migrations.AddField(
            model_name='formateur',
            name='filiere',
            field=models.ManyToManyField(blank=True, related_name='formateur', to='academique.filiere'),
        ),
        migrations.AddField(
            model_name='formateur',
            name='specialite',
            field=models.ManyToManyField(blank=True, related_name='formateur', to='academique.specialite'),
        ),
    ]
