# Generated by Django 5.2.17 on 2026-09-06 21:47

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_remove_formateur_filiere_remove_formateur_specialite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='acte_naissance',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='etudiants/actes_naissance/'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='cni',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='etudiants/cni/'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='diplome',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='etudiants/diplomes/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='cni',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='personnel/cni/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='diplome',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='personnel/diplomes/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='motivation',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='personnel/motivations/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='recommandation',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='personnel/recommandations/'),
        ),
    ]
