# Generated by Django 5.2.17 on 2026-08-09 02:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academique', '0001_initial'),
        ('utilisateurs', '0002_delete_configurationmatricule_etudiant_classe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
                ('est_tresorerie', models.BooleanField(default=False, help_text='Coché pour les mouvements de trésorerie interne (ex. dépôt bancaire) : ils sortent de la caisse mais ne sont pas de vraies charges de fonctionnement, donc exclus des totaux de dépenses du tableau de bord.')),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépense',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=80)),
                ('obligatoire_a_inscription', models.BooleanField(default=False)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Type de paiement',
                'verbose_name_plural': 'Types de paiement',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Bourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisme', models.CharField(blank=True, max_length=150, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='bourses/justificatifs/')),
                ('type_reduction', models.CharField(blank=True, choices=[('pourcentage', 'Pourcentage'), ('montant_fixe', 'Montant fixe')], help_text="Laisser vide pour utiliser le réglage par défaut de l'institut.", max_length=15, null=True)),
                ('valeur_reduction', models.DecimalField(blank=True, decimal_places=2, help_text="Laisser vide pour utiliser le réglage par défaut de l'institut.", max_digits=10, null=True)),
                ('date_attribution', models.DateField(default=django.utils.timezone.localdate)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bourse', to='utilisateurs.etudiant')),
            ],
            options={
                'verbose_name': 'Bourse',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CaisseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_session', models.DateField(default=django.utils.timezone.localdate, unique=True)),
                ('heure_ouverture', models.TimeField(default=django.utils.timezone.localtime)),
                ('heure_fermeture', models.TimeField(blank=True, null=True)),
                ('solde_ouverture', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solde_reel_fermeture', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('FERMEE', 'Fermée')], default='OUVERTE', max_length=8)),
                ('observation', models.TextField(blank=True, help_text="Justification en cas d'écart de caisse.")),
                ('fermee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_fermees', to=settings.AUTH_USER_MODEL)),
                ('ouverte_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_ouvertes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'ordering': ['-date_session'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_depense', models.DateField(default=django.utils.timezone.localdate)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement')], max_length=10)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='depenses/justificatifs/%Y/%m/')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('PAYEE', 'Payée')], default='EN_ATTENTE', max_length=10)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_approuvees', to=settings.AUTH_USER_MODEL)),
                ('caisse_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='finances.caissesession')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='finances.categoriedepense')),
                ('demande_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_demandees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense',
                'ordering': ['-date_depense', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('date_inscription', models.DateField(default=django.utils.timezone.localdate)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=12)),
                ('annee_academique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academique.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='academique.classe')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_creees', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='utilisateurs.etudiant')),
            ],
            options={
                'verbose_name': 'Inscription',
                'ordering': ['-date_inscription'],
                'unique_together': {('etudiant', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('annee_academique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='academique.anneeacademique')),
                ('niveaux', models.ManyToManyField(blank=True, help_text="Laisser vide = s'applique à tous les niveaux.", related_name='tarifs', to='academique.niveau')),
                ('specialites', models.ManyToManyField(blank=True, help_text="Laisser vide = s'applique à toutes les spécialités.", related_name='tarifs', to='academique.specialite')),
                ('type_paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='finances.typepaiement')),
            ],
            options={
                'verbose_name': 'Tarif',
                'ordering': ['-annee_academique', 'type_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField(default=django.utils.timezone.localdate)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement'), ('MOBILE', 'Mobile Money')], max_length=10)),
                ('numero_recu', models.CharField(blank=True, max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('VALIDE', 'Validé'), ('ANNULE', 'Annulé'), ('REMBOURSE', 'Remboursé')], default='VALIDE', max_length=10)),
                ('caisse_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='finances.caissesession')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='finances.inscription')),
                ('type_paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='finances.typepaiement')),
            ],
            options={
                'verbose_name': 'Paiement',
                'ordering': ['-date_paiement', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FraisInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_application', models.DateField(default=django.utils.timezone.localdate)),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frais_ajoutes', to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='finances.inscription')),
                ('type_paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frais_appliques', to='finances.typepaiement')),
            ],
            options={
                'verbose_name': "Frais d'inscription",
                'verbose_name_plural': "Frais d'inscription",
                'ordering': ['type_paiement__ordre'],
                'unique_together': {('inscription', 'type_paiement')},
            },
        ),
    ]
