# Generated by Django 5.2.17 on 2026-08-29 14:33

import apps.finances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caissesession',
            name='heure_ouverture',
            field=models.TimeField(default=apps.finances.models.heure_actuelle),
        ),
    ]
