# Generated by Django 5.2.17 on 2026-08-29 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_caissesession_heure_ouverture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caissesession',
            name='date_session',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
