# Generated by Django 5.2.17 on 2026-09-06 21:47

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_caissesession_date_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='justificatif',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='depenses/justificatifs/%Y/%m/'),
        ),
    ]
