# Generated by Django 5.2.17 on 2026-08-08 15:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academique', '0001_initial'),
        ('utilisateurs', '0002_delete_configurationmatricule_etudiant_classe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('poids', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Poids dans le calcul de la moyenne (ex: 0.40 pour 40%). La somme des poids actifs doit faire 1.00.', max_digits=4)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Type d'évaluation",
                'verbose_name_plural': "Types d'évaluation",
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Deliberation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('ANNEE', 'Année complète')], max_length=5)),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('credits_obtenus', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('credits_requis', models.DecimalField(decimal_places=2, help_text='Valeur figée au moment du calcul (copie du paramètre institut à cet instant).', max_digits=6)),
                ('seuil_admission', models.DecimalField(decimal_places=2, help_text="Note d'admission minimale utilisée pour ce calcul (figée elle aussi).", max_digits=4)),
                ('decision', models.CharField(choices=[('ADMIS', 'Admis'), ('RATTRAPAGE', 'Rattrapage'), ('REDOUBLANT', 'Redoublant'), ('INCOMPLET', 'Incomplet (notes manquantes)')], max_length=12)),
                ('matieres_non_validees', models.JSONField(blank=True, default=list, help_text='Liste figée des matières à rattraper : nom, moyenne obtenue, coefficient.')),
                ('verrouillee', models.BooleanField(default=False, help_text='Une délibération verrouillée ne peut plus être recalculée automatiquement.')),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('date_premiere_deliberation', models.DateTimeField(auto_now_add=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberations', to='academique.anneeacademique')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberations', to='utilisateurs.etudiant')),
            ],
            options={
                'verbose_name': 'Délibération',
                'verbose_name_plural': 'Délibérations',
                'ordering': ['etudiant'],
                'unique_together': {('etudiant', 'annee_academique', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], max_length=2)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academique.anneeacademique')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='utilisateurs.etudiant')),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to='utilisateurs.formateur')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academique.matiere')),
                ('type_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='notes.typeevaluation')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['etudiant', 'matiere', 'semestre'],
                'unique_together': {('etudiant', 'matiere', 'annee_academique', 'semestre', 'type_evaluation')},
            },
        ),
    ]
