# Generated by Django 5.2.17 on 2026-08-07 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Année académique',
                'verbose_name_plural': 'Années académiques',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectif', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['specialite'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('cycle', models.CharField(choices=[('bts', 'BTS'), ('licence', 'LICENCE'), ('master', 'MASTER'), ('doctorat', 'DOCTORAT'), ('plus', 'PLUS')], max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('capacite', models.PositiveIntegerField(default=0)),
                ('localisation', models.CharField(max_length=50)),
                ('equipements', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('indisponible', 'Indisponible'), ('construction', 'En construction'), ('maintenance', 'En maintenance'), ('fermee', 'Fermée')], default='disponible', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('avertissement', 'Avertissement'), ('blame', 'Blâme'), ('exclusion_tem', 'Exclusion temporaire'), ('exclusion_def', 'Exclusion définitive')], default='avertissement', max_length=20)),
                ('gravite', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('grave', 'Grave'), ('tres_grave', 'Très grave')], default='grave', max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entree_en_vigueur', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sanction',
                'verbose_name_plural': 'Sanctions',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Type de salle',
                'verbose_name_plural': 'Types de salle',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], default='S1', max_length=2)),
                ('titre', models.CharField(blank=True, max_length=150)),
                ('semaine_debut', models.DateField(null=True)),
                ('semaine_fin', models.DateField(null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='academique.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='academique.classe')),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=10)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filieres_responsable', to='utilisateurs.personnel')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classe', to='academique.filiere'),
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('volume_horaire', models.PositiveIntegerField(default=1)),
                ('credit', models.PositiveIntegerField(default=1)),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], max_length=2)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('niveau', models.ManyToManyField(blank=True, related_name='matieres', to='academique.niveau')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classe', to='academique.niveau'),
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_seance', models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques'), ('EX', 'Examen')], default='CM', max_length=2)),
                ('jour', models.CharField(choices=[('LUN', 'Lundi'), ('MAR', 'Mardi'), ('MER', 'Mercredi'), ('JEU', 'Jeudi'), ('VEN', 'Vendredi'), ('SAM', 'Samedi'), ('DIM', 'Dimanche')], default='LUN', max_length=3)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('emploi_du_temps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='academique.emploidutemps')),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='utilisateurs.formateur')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='academique.matiere')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='academique.salle')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=10)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialites', to='academique.filiere')),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='matiere',
            name='specialite',
            field=models.ManyToManyField(blank=True, related_name='matieres', to='academique.specialite'),
        ),
        migrations.AddField(
            model_name='classe',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classe', to='academique.specialite'),
        ),
        migrations.AddField(
            model_name='salle',
            name='type_salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salles', to='academique.typesalle'),
        ),
    ]
