# Generated by Django 5.2.17 on 2026-08-09 15:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        ('utilisateurs', '0002_delete_configurationmatricule_etudiant_classe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCertificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('auto_generable', models.BooleanField(default=False, help_text="Si coché, l'étudiant peut générer ce certificat lui-même en libre-service.")),
            ],
            options={
                'verbose_name': 'Type de certificat',
                'verbose_name_plural': 'Types de certificat',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_diplome', models.CharField(blank=True, max_length=30, unique=True)),
                ('mention', models.CharField(blank=True, max_length=50, null=True)),
                ('date_obtention', models.DateField(default=django.utils.timezone.localdate)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents/diplomes/')),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('revoque', 'Révoqué')], default='valide', max_length=10)),
                ('motif_revocation', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('deliberation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='diplome', to='notes.deliberation')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='utilisateurs.etudiant')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diplomes_generes', to=settings.AUTH_USER_MODEL)),
                ('signe_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diplomes_signes', to='utilisateurs.personnel')),
            ],
            options={
                'verbose_name': 'Diplôme',
                'ordering': ['-date_obtention'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('fichier', models.FileField(upload_to='documents/autres/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_ajoutes', to=settings.AUTH_USER_MODEL)),
                ('concerne_etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='utilisateurs.etudiant')),
                ('concerne_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='utilisateurs.personnel')),
            ],
            options={
                'verbose_name': 'Document',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('date_emission', models.DateField(default=django.utils.timezone.localdate)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents/certificats/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='utilisateurs.etudiant')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificats_generes', to=settings.AUTH_USER_MODEL)),
                ('type_certificat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificats', to='documents.typecertificat')),
            ],
            options={
                'verbose_name': 'Certificat',
                'ordering': ['-date_emission'],
            },
        ),
    ]
