# Generated by Django 5.2.17 on 2026-09-06 21:47

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificat',
            name='fichier',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents/certificats/'),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='fichier',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents/diplomes/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents/autres/'),
        ),
    ]
