# Generated by Django 5.2.17 on 2026-08-31 17:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academique', '0001_initial'),
        ('utilisateurs', '0003_remove_formateur_filiere_remove_formateur_specialite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('biographie', models.TextField(blank=True, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bibliotheque/auteurs/')),
            ],
            options={
                'verbose_name': 'Auteur',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Éditeur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('etat', models.CharField(choices=[('BON', 'Bon'), ('MOYEN', 'Moyen'), ('ABIME', 'Abîmé'), ('TRES_ABIME', 'Très abîmé')], default='BON', max_length=15)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EMPRUNTE', 'Emprunté'), ('RESERVE', 'Réservé'), ('PERDU', 'Perdu'), ('ENDOMMAGE', 'Endommagé'), ('EN_REPARATION', 'En réparation'), ('RETIRE', 'Retiré')], default='DISPONIBLE', max_length=15)),
                ('date_acquisition', models.DateField(default=django.utils.timezone.localdate)),
            ],
            options={
                'verbose_name': 'Exemplaire',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('personne_contact', models.CharField(blank=True, max_length=150, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='RegleBibliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_adherent', models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('PERSONNEL', 'Personnel'), ('FORMATEUR', 'Formateur')], max_length=15, unique=True)),
                ('nb_emprunts_max', models.PositiveIntegerField(default=3)),
                ('duree_emprunt_jours', models.PositiveIntegerField(default=14)),
                ('nb_renouvellements_max', models.PositiveIntegerField(default=1)),
                ('penalite_par_jour_retard', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('penalite_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('penalite_perte', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('penalite_deterioration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duree_retrait_reservation_jours', models.PositiveIntegerField(default=2, help_text="Délai laissé à l'adhérent pour retirer un exemplaire réservé devenu disponible.")),
            ],
            options={
                'verbose_name': 'Règle de bibliothèque',
                'verbose_name_plural': 'Règles de bibliothèque',
            },
        ),
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EXPIRE', 'Expiré'), ('DESACTIVE', 'Désactivé')], default='ACTIF', max_length=15)),
                ('motif_suspension', models.TextField(blank=True, null=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('etudiant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adherent_bibliotheque', to='utilisateurs.etudiant')),
                ('formateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adherent_bibliotheque', to='utilisateurs.formateur')),
                ('personnel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adherent_bibliotheque', to='utilisateurs.personnel')),
            ],
            options={
                'verbose_name': 'Adhérent',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='bibliotheque.categorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('date_emprunt', models.DateField(default=django.utils.timezone.localdate)),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('RETOURNE', 'Retourné'), ('EN_RETARD', 'En retard'), ('PERDU', 'Perdu'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=15)),
                ('nb_renouvellements', models.PositiveIntegerField(default=0)),
                ('observations', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to='bibliotheque.adherent')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprunts_enregistres', to=settings.AUTH_USER_MODEL)),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to='bibliotheque.exemplaire')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'ordering': ['-date_emprunt'],
            },
        ),
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('date_acquisition', models.DateField(default=django.utils.timezone.localdate)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('statut', models.CharField(choices=[('EN_PREPARATION', 'En préparation'), ('COMMANDEE', 'Commandée'), ('RECUE', 'Reçue'), ('PARTIELLEMENT_RECUE', 'Partiellement reçue'), ('ANNULEE', 'Annulée')], default='EN_PREPARATION', max_length=25)),
                ('observations', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisitions_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisitions', to='bibliotheque.fournisseur')),
            ],
            options={
                'verbose_name': 'Acquisition',
                'ordering': ['-date_acquisition'],
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inventaire', models.DateField(default=django.utils.timezone.localdate)),
                ('zone_concernee', models.CharField(blank=True, help_text='Ex: Rayon A, Bibliothèque entière...', max_length=150, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='EN_COURS', max_length=15)),
                ('observations', models.TextField(blank=True, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventaire',
                'ordering': ['-date_inventaire'],
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salle', models.CharField(blank=True, max_length=100, null=True)),
                ('rayon', models.CharField(blank=True, max_length=50, null=True)),
                ('etagere', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Localisation',
                'unique_together': {('salle', 'rayon', 'etagere')},
            },
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='localisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exemplaires', to='bibliotheque.localisation'),
        ),
        migrations.CreateModel(
            name='Penalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_penalite', models.CharField(choices=[('RETARD', 'Retard'), ('PERTE', 'Perte'), ('DETERIORATION', 'Détérioration')], max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payee', models.BooleanField(default=False)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('emprunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalites', to='bibliotheque.emprunt')),
            ],
            options={
                'verbose_name': 'Pénalité',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('type_ressource', models.CharField(choices=[('LIVRE', 'Livre'), ('REVUE', 'Revue / Périodique'), ('MEMOIRE', 'Mémoire / Travail académique'), ('NUMERIQUE', 'Ressource numérique'), ('AUTRE', 'Autre')], default='LIVRE', max_length=15)),
                ('titre', models.CharField(max_length=255)),
                ('sous_titre', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn_issn', models.CharField(blank=True, max_length=30, null=True)),
                ('annee_publication', models.PositiveIntegerField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=50, null=True)),
                ('langue', models.CharField(blank=True, max_length=50, null=True)),
                ('mots_cles', models.CharField(blank=True, help_text='Séparés par des virgules', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='bibliotheque/couvertures/')),
                ('fichier_numerique', models.FileField(blank=True, null=True, upload_to='bibliotheque/numerique/')),
                ('retiree', models.BooleanField(default=False, help_text='Ressource retirée du catalogue actif (jamais supprimée).')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('auteurs', models.ManyToManyField(blank=True, related_name='ressources', to='bibliotheque.auteur')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources', to='bibliotheque.categorie')),
                ('editeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources', to='bibliotheque.editeur')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources_bibliotheque', to='academique.filiere')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources_bibliotheque', to='academique.specialite')),
            ],
            options={
                'verbose_name': 'Ressource',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('DISPONIBLE', 'Disponible'), ('RETIREE', 'Retirée'), ('EXPIREE', 'Expirée'), ('ANNULEE', 'Annulée'), ('TERMINEE', 'Terminée')], default='EN_ATTENTE', max_length=15)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='bibliotheque.adherent')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='bibliotheque.ressource')),
            ],
            options={
                'verbose_name': 'Réservation',
                'ordering': ['date_reservation'],
            },
        ),
        migrations.CreateModel(
            name='LigneAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acquisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='bibliotheque.acquisition')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_acquisition', to='bibliotheque.ressource')),
            ],
            options={
                'verbose_name': "Ligne d'acquisition",
            },
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exemplaires', to='bibliotheque.ressource'),
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_constate', models.CharField(choices=[('PRESENT', 'Présent'), ('INTROUVABLE', 'Introuvable'), ('ENDOMMAGE', 'Endommagé'), ('INCOHERENT', 'Incohérent'), ('A_VERIFIER', 'À vérifier')], default='A_VERIFIER', max_length=15)),
                ('observation', models.TextField(blank=True, null=True)),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_inventaire', to='bibliotheque.exemplaire')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='bibliotheque.inventaire')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'unique_together': {('inventaire', 'exemplaire')},
            },
        ),
    ]
