# Generated by Django 5.2.17 on 2026-08-08 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academique', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationMatricule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_profil', models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('PERSONNEL', 'Personnel')], max_length=20, unique=True)),
                ('prefixe', models.CharField(default='MAT', max_length=10)),
                ('inclure_annee', models.BooleanField(default=True)),
                ('nombre_chiffres', models.PositiveIntegerField(default=4)),
                ('separateur', models.CharField(default='-', max_length=3)),
                ('compteur', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ParametreInstitut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default="IFP Perle d'Or", max_length=200)),
                ('sigle', models.CharField(blank=True, max_length=50, null=True)),
                ('slogan', models.CharField(blank=True, max_length=200, null=True)),
                ('type_etablissement', models.CharField(choices=[('public', 'Public'), ('prive', 'Privé'), ('semi_public', 'Semi-public')], default='prive', max_length=20)),
                ('directeur_general', models.CharField(blank=True, max_length=150, null=True)),
                ('date_creation_institut', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institut/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='institut/favicon/')),
                ('couleur_primaire', models.CharField(default='#1e3a8a', max_length=7)),
                ('couleur_secondaire', models.CharField(default='#f59e0b', max_length=7)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('boite_postale', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_agrement', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_rccm', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_contribuable', models.CharField(blank=True, max_length=100, null=True)),
                ('representant_legal', models.CharField(blank=True, max_length=150, null=True)),
                ('note_admission_minimale', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('credits_requis_semestre', models.PositiveIntegerField(default=30)),
                ('credits_requis_annee', models.PositiveIntegerField(default=60)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Paramètre de l'institut",
                'verbose_name_plural': "Paramètres de l'institut",
            },
        ),
        migrations.CreateModel(
            name='ArchiveAnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_etudiants', models.PositiveIntegerField(default=0)),
                ('nb_notes', models.PositiveIntegerField(default=0)),
                ('nb_deliberations', models.PositiveIntegerField(default=0)),
                ('nb_admis', models.PositiveIntegerField(default=0)),
                ('nb_redoublants', models.PositiveIntegerField(default=0)),
                ('date_archivage', models.DateTimeField(auto_now_add=True)),
                ('notes_archivage', models.TextField(blank=True, null=True)),
                ('annee_academique', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='academique.anneeacademique')),
                ('archivee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives_realisees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Archive d'année académique",
                'verbose_name_plural': "Archives d'années académiques",
                'ordering': ['-date_archivage'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('info', 'Information'), ('succes', 'Succès'), ('avertissement', 'Avertissement'), ('erreur', 'Erreur')], default='info', max_length=20)),
                ('lien', models.CharField(blank=True, help_text='Chemin frontend à ouvrir au clic', max_length=255, null=True)),
                ('lue', models.BooleanField(default=False)),
                ('email_envoye', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Sauvegarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='sauvegardes/')),
                ('nom_fichier', models.CharField(blank=True, max_length=255, null=True)),
                ('taille_octets', models.BigIntegerField(blank=True, null=True)),
                ('type_sauvegarde', models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], default='manuelle', max_length=20)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('reussie', 'Réussie'), ('echouee', 'Échouée')], default='en_cours', max_length=20)),
                ('message_erreur', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('declenchee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sauvegardes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sauvegarde',
                'verbose_name_plural': 'Sauvegardes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
