# Generated by Django 5.2.17 on 2026-08-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametreinstitut',
            name='type_reduction_bourse_defaut',
            field=models.CharField(choices=[('pourcentage', 'Pourcentage'), ('montant_fixe', 'Montant fixe')], default='pourcentage', max_length=15),
        ),
        migrations.AddField(
            model_name='parametreinstitut',
            name='valeur_reduction_bourse_defaut',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Si pourcentage : entrer un nombre entre 0 et 100. Si montant fixe : entrer une somme.', max_digits=10),
        ),
    ]
