# Generated by Django 5.2.17 on 2026-08-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_parametreinstitut_type_reduction_bourse_defaut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationmatricule',
            name='type_profil',
            field=models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('PERSONNEL', 'Personnel'), ('DIPLOME', 'Diplôme'), ('CERTIFICAT', 'Certificat')], max_length=20, unique=True),
        ),
    ]
