# Generated by Django 5.2.17 on 2026-08-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_alter_configurationmatricule_type_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametreinstitut',
            name='duree_emprunt_jours',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='parametreinstitut',
            name='nb_emprunts_max_simultanes',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='parametreinstitut',
            name='penalite_par_jour_retard',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
