# Generated by Django 5.2.17 on 2026-08-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0004_parametreinstitut_duree_emprunt_jours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('date_derniere_activation', models.DateTimeField(blank=True, null=True)),
                ('dernier_code_utilise', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'Abonnement',
            },
        ),
    ]
