# Generated by Django 5.2.17 on 2026-08-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0005_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametreinstitut',
            name='inscriptions_en_ligne',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametreinstitut',
            name='notation_enseignants_en_ligne',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametreinstitut',
            name='notifications_parents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parametreinstitut',
            name='redoublement_automatique',
            field=models.BooleanField(default=False),
        ),
    ]
