# Generated by Django 5.2.17 on 2026-08-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0006_parametreinstitut_inscriptions_en_ligne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationmatricule',
            name='type_profil',
            field=models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('PERSONNEL', 'Personnel'), ('DIPLOME', 'Diplôme'), ('CERTIFICAT', 'Certificat'), ('RESSOURCE', 'Ressource bibliothèque'), ('EXEMPLAIRE', 'Exemplaire bibliothèque'), ('ADHERENT', 'Adhérent bibliothèque'), ('EMPRUNT', 'Emprunt bibliothèque'), ('RESERVATION', 'Réservation bibliothèque'), ('ACQUISITION', 'Acquisition bibliothèque')], max_length=20, unique=True),
        ),
    ]
