# Generated by Django 5.2.17 on 2026-09-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0007_alter_configurationmatricule_type_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='date_activation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
